### ISSUE TITLE
My Vehicle is displaying wrong next service due date

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/CA-Portal#58]
The "Next Service Due" date and mileage are calculated using the values given by the API.
The date should be "lofLastDate" + ("lofIntervalDays" * 86400).

The mileage is calculated correctly

?? Is there any flagging taking place when the "lofIsDue" is true?

**Comment by DanielCaspers** [comment]
@scaspers , I checked in a fix. Feel free to review this pull request, pull down a new build, and double check my math. Sorry for this missed detail. If it is now as expected, please close it. This one's on the house :)

The only "flagging" is that because I am mapping your models to my own local ones, based on whether or not all of the data is in a sane state. Here's the whole adjusted code snippet in context straight back from the HTTP request. Click image to view code in full screen.

![image](https://user-images.githubusercontent.com/6056563/106996287-4d77ca80-6746-11eb-9f16-28d011bcec29.png)

**Comment by scaspers** [comment]
All good
