### ISSUE TITLE
Schedule date issues with DST

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/CA-Portal#62]
If I pick a schedule date after 3/13/21 then the date sent if off by -1 day

**Comment by DanielCaspers** [comment]
We later determined that the DST issues were related to Serverside date parsing. It only looked like a client-side date issue because the wrong date shows up in Chrome's dev tools "preview" window, since the HTTP 201 Created response goes within the "Preview" window, but the original request can be seen as correct within different tabs. 

Other browsers, such as Firefox, make the delineation between requests and responses clearer, which was useful in determining this issue.

**Comment by scaspers** [comment]
Issue corrected on the back end process so that DST changes are accounted for.
